const $=s=>document.querySelector(s);let page=1,model={items:[],total:0,pageSize:50},timer,analyticsData={};
const num=v=>v==null?'null':new Intl.NumberFormat('ko-KR',{maximumFractionDigits:2}).format(v);const date=v=>v?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'-';const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function request(url,options){const r=await fetch(url,options);const d=await r.json();if(!r.ok)throw Error(d.error||'요청 실패');return d;}
function query(){return new URLSearchParams({q:$('#search').value,category:$('#category').value,state:$('#state').value,page,pageSize:50});}
function badge(p){return p.lifecycleStatus==='deleted'?'삭제 감지':p.lifecycleStatus==='sold_out'?'품절':p.lifecycleStatus==='active'?'판매 중':'신규';}
function render(){const rows=model.items;$('#count').textContent=`${model.total}개 중 ${(page-1)*model.pageSize+1}-${Math.min(page*model.pageSize,model.total)}개`;$('#products').innerHTML=rows.length?rows.map(p=>{const discount=p.listPrice&&p.salePrice&&p.listPrice>p.salePrice?Math.round((1-p.salePrice/p.listPrice)*100):null;return `<tr data-product="${esc(p.id)}"><td>${esc(p.id)}</td><td><a href="${esc(p.url)}" target="_blank" rel="noreferrer">${esc(p.name)}</a></td><td>${esc(p.category||'-')}</td><td>${num(p.salePrice)}</td><td>${num(p.listPrice)}</td><td>${discount==null?'null':discount+'%'}</td><td>${p.reviewCount==null?'null':`${num(p.reviewCount)} / ${num(p.rating)}`}</td><td><span class="badge ${esc(p.lifecycleStatus)}">${badge(p)}</span></td><td>${date(p.lastSeenAt)}</td></tr>`}).join(''):'<tr><td colspan="9" class="empty">조건에 맞는 상품이 없습니다.</td></tr>';$('#page-info').textContent=`${page} / ${Math.max(1,Math.ceil(model.total/model.pageSize))}`;$('#prev').disabled=page===1;$('#next').disabled=page*model.pageSize>=model.total;}
function svgBars(values){if(!values.length)return '변동 이력이 쌓이면 표시됩니다.';const max=Math.max(...values.map(x=>x.value),1);return `<div class="bars">${values.map(x=>`<div class="bar-row"><span>${esc(x.category)}</span><i><b style="width:${Math.max(2,x.value/max*100)}%"></b></i><strong>${num(x.value)}</strong></div>`).join('')}</div>`;}
function spark(history){if(history.length<2)return '<span class="muted">최소 2회 수집 후 추이가 표시됩니다.</span>';const vals=history.map(x=>x.salePrice).filter(v=>v!=null),min=Math.min(...vals),max=Math.max(...vals),w=280,h=54;const pts=history.map((x,i)=>`${i/(history.length-1)*w},${h-5-(x.salePrice-min)/Math.max(1,max-min)*(h-14)}`).join(' ');return `<svg viewBox="0 0 ${w} ${h}" role="img"><polyline points="${pts}" fill="none" stroke="#5b5ce2" stroke-width="3"/><text x="0" y="12">${num(max)}</text><text x="0" y="52">${num(min)}</text></svg>`;}
function renderTrend(history){if(!history.length){$('#price-chart').textContent='수집 이력이 아직 없습니다.';return;}$('#price-chart').innerHTML=spark(history);const last=history.at(-1);$('#trend-meta').textContent=`최근 판매가 ${num(last.salePrice)} · 소비자가 ${num(last.listPrice)} · 구매평 ${num(last.reviewCount)} · 평균 별점 ${num(last.rating)} (별점 없는 구매평은 평균에서 제외)`;}
function renderLeaderTrends(leaders){
 const host=$('#price-chart'),meta=$('#trend-meta');
 if(!leaders.length){host.textContent='최소 두 번의 3시간 단위 수집 후 가격 변동 상위 5개 추이가 표시됩니다.';meta.textContent='다음 수집 결과가 쌓이면 실제 가격 변화가 큰 상품부터 표시합니다.';return;}
 const colors=['#2f7d32','#a64b00','#b88a00','#2456a6','#7c3aed'],times=[...new Set(leaders.flatMap(x=>x.points.map(p=>p.at)))].sort(),left=58,right=760,top=26,bottom=266,width=980,height=320;
 const series=leaders.map((item,index)=>{const first=item.points.find(p=>Number.isFinite(p.salePrice));const base=first?.salePrice||1;return {...item,color:colors[index],values:item.points.map(p=>({at:p.at,value:p.listPrice>0?p.salePrice/p.listPrice*100:p.salePrice/base*100}))};});
 const values=series.flatMap(x=>x.values.map(p=>p.value)),min=Math.floor(Math.min(...values,70)/5)*5,max=Math.ceil(Math.max(...values,100)/5)*5,range=Math.max(5,max-min),x=at=>left+(times.indexOf(at)/Math.max(1,times.length-1))*(right-left),y=value=>bottom-(value-min)/range*(bottom-top),formatAt=at=>new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit'}).format(new Date(at));
 const grid=Array.from({length:5},(_,i)=>{const value=min+(range*i/4),py=y(value);return '<line x1="'+left+'" y1="'+py+'" x2="'+right+'" y2="'+py+'" stroke="#e5e7eb"/><text x="'+(left-10)+'" y="'+(py+4)+'" text-anchor="end" fill="#6b7280" font-size="12">'+Math.round(value)+'%</text>';}).join('');
 const tickIndexes=[0,Math.floor((times.length-1)/2),times.length-1].filter((v,i,a)=>a.indexOf(v)===i),ticks=tickIndexes.map(i=>'<text x="'+x(times[i])+'" y="'+(bottom+24)+'" text-anchor="middle" fill="#6b7280" font-size="12">'+formatAt(times[i])+'</text>').join('');
 const lines=series.map(s=>{const points=s.values.map(p=>({x:x(p.at),y:y(p.value)}));const path=points.map((p,i)=>i?'H'+p.x+'V'+p.y:'M'+p.x+' '+p.y).join('');const last=points.at(-1);return '<path d="'+path+'" fill="none" stroke="'+s.color+'" stroke-width="3" stroke-linejoin="round"/><circle cx="'+last.x+'" cy="'+last.y+'" r="4" fill="'+s.color+'"/><text x="'+(last.x+9)+'" y="'+(last.y+4)+'" fill="'+s.color+'" font-size="12" font-weight="700">'+esc(s.name)+'</text>';}).join('');
 host.innerHTML='<svg viewBox="0 0 '+width+' '+height+'" role="img" aria-label="가격 변동 상위 5개 상품의 3시간 단위 추이"><rect x="0" y="0" width="'+width+'" height="'+height+'" fill="white"/>'+grid+'<line x1="'+left+'" y1="'+bottom+'" x2="'+right+'" y2="'+bottom+'" stroke="#cbd5e1"/>'+ticks+lines+'</svg>';
 meta.textContent='가격 변화 폭이 큰 5개 상품을 판매가/소비자가 비율로 비교합니다. 계단선은 3시간 수집 시점에만 가격이 갱신되기 때문입니다.';
}
async function loadAnalytics(){const [data,leaders]=await Promise.all([request('/api/analytics'),request('/api/trends')]);analyticsData=data;const cats=[...new Set(data.categories.map(x=>x.category).filter(Boolean))].sort(),selected=$('#category').value;$('#category').innerHTML='<option value="">전체 카테고리</option>'+cats.map(x=>`<option value="${esc(x)}" ${x===selected?'selected':''}>${esc(x)}</option>`).join('');$('#category-chart').innerHTML=svgBars(data.categories);$('#discounts').innerHTML=data.discounts.length?data.discounts.map(p=>'<tr><td>'+esc(p.id)+' '+esc(p.name)+'</td><td>'+num(p.salePrice)+'</td><td>'+num(p.listPrice)+'</td><td>'+num(p.discount)+'%</td></tr>').join(''):'<tr><td colspan="4" class="empty">할인 상품이 없습니다.</td></tr>';$('#movers').innerHTML=data.movers.length?data.movers.slice(0,5).map(p=>'<div class="mover"><span>'+esc(p.name)+'</span><b>'+num(p.change)+'</b></div>').join(''):'가격 변동이 감지되면 상위 5개를 표시합니다.';renderLeaderTrends(leaders);}
async function load(){const [summary,list]=await Promise.all([request('/api/summary'),request('/api/products?'+query())]);model=list;$('#total').textContent=summary.total??0;$('#available').textContent=summary.available??0;$('#soldout').textContent=summary.soldout??0;$('#deleted').textContent=summary.deleted??0;$('#last-seen').textContent=summary.lastSeen?`마지막 상품 확인: ${date(summary.lastSeen)}`:'아직 수집한 상품이 없습니다.';$('#collect').disabled=summary.collecting;$('#collect').textContent=summary.collecting?'수집 중...':'전체 다시 수집';$('#notice').textContent=summary.collecting?'전체 카테고리와 모든 페이지를 수집 중입니다.':'';render();await loadAnalytics();}
async function boot(){const auth=await request('/api/auth');$('#app').classList.remove('hidden');$('#collect').hidden=!auth.authorized;$('#logout').hidden=!auth.authorized;$('#admin-login').hidden=auth.authorized;await load();}
$('#login-form').onsubmit=async e=>{e.preventDefault();try{await request('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token:$('#token').value})});$('#login').classList.add('hidden');await boot();}catch(e){$('#login-error').textContent=e.message;}};$('#admin-login').onclick=()=>{$('#login').classList.remove('hidden');};$('#logout').onclick=async()=>{await request('/api/logout',{method:'POST'});location.reload();};$('#collect').onclick=async()=>{const button=$('#collect');button.disabled=true;button.classList.remove('completed');button.classList.add('collecting');button.textContent='수집 중...';$('#notice').textContent='전체 상품을 수집 중입니다. 완료되면 최신 결과를 표시합니다.';try{const before=(await request('/api/summary')).lastRun?.id;let launchError;request('/api/collect',{method:'POST'}).catch(error=>{launchError=error;});let completed;for(let seconds=1;seconds<=180;seconds++){await new Promise(resolve=>setTimeout(resolve,1000));if(launchError)throw launchError;const status=await request('/api/summary'),run=status.lastRun;button.textContent=`수집 중... ${seconds}초`;if(run&&run.id!==before&&!status.collecting){if(run.status==='success'){completed=run;break;}throw Error(run.error||'수집에 실패했습니다.');}}if(!completed)throw Error('수집 시간이 초과되었습니다.');page=1;button.classList.remove('collecting');button.classList.add('completed');button.textContent='수집 완료';$('#notice').textContent=`수집 완료: ${num(completed.scanned??0)}개 상품을 확인했습니다.`;load().catch(error=>console.error('수집 후 화면 갱신 실패',error));setTimeout(()=>{button.classList.remove('completed');button.disabled=false;button.textContent='전체 다시 수집';},8000);}catch(e){button.classList.remove('collecting');button.disabled=false;button.textContent='다시 시도';$('#notice').textContent='수집 실패: '+e.message;}};['category','state'].forEach(id=>$('#'+id).onchange=()=>{page=1;load();});$('#search').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{page=1;load();},300);};$('#prev').onclick=()=>{page--;load();};$('#next').onclick=()=>{page++;load();};boot().catch(e=>console.error(e));
