const $=s=>document.querySelector(s);let page=1,model={items:[],total:0,pageSize:50},timer,analyticsData={};
const num=v=>v==null?'null':new Intl.NumberFormat('ko-KR',{maximumFractionDigits:2}).format(v);const date=v=>v?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'-';const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function request(url,options){const r=await fetch(url,options);if(r.status===401){$('#app').classList.add('hidden');$('#login').classList.remove('hidden');throw Error('로그인이 필요합니다.');}const d=await r.json();if(!r.ok)throw Error(d.error||'요청 실패');return d;}
function query(){return new URLSearchParams({q:$('#search').value,category:$('#category').value,state:$('#state').value,page,pageSize:50});}
function badge(p){return p.lifecycleStatus==='deleted'?'삭제 감지':p.lifecycleStatus==='sold_out'?'품절':p.lifecycleStatus==='active'?'판매 중':'신규';}
function render(){const rows=model.items;$('#count').textContent=`${model.total}개 중 ${(page-1)*model.pageSize+1}-${Math.min(page*model.pageSize,model.total)}개`;$('#products').innerHTML=rows.length?rows.map(p=>{const discount=p.listPrice&&p.salePrice&&p.listPrice>p.salePrice?Math.round((1-p.salePrice/p.listPrice)*100):null;return `<tr data-product="${esc(p.id)}"><td>${esc(p.id)}</td><td><a href="${esc(p.url)}" target="_blank" rel="noreferrer">${esc(p.name)}</a></td><td>${esc(p.category||'-')}</td><td>${num(p.salePrice)}</td><td>${num(p.listPrice)}</td><td>${discount==null?'null':discount+'%'}</td><td>${p.reviewCount==null?'null':`${num(p.reviewCount)} / ${num(p.rating)}`}</td><td><span class="badge ${esc(p.lifecycleStatus)}">${badge(p)}</span></td><td>${date(p.lastSeenAt)}</td></tr>`}).join(''):'<tr><td colspan="9" class="empty">조건에 맞는 상품이 없습니다.</td></tr>';$('#page-info').textContent=`${page} / ${Math.max(1,Math.ceil(model.total/model.pageSize))}`;$('#prev').disabled=page===1;$('#next').disabled=page*model.pageSize>=model.total;}
function svgBars(values){if(!values.length)return '변동 이력이 쌓이면 표시됩니다.';const max=Math.max(...values.map(x=>x.value),1);return `<div class="bars">${values.map(x=>`<div class="bar-row"><span>${esc(x.category)}</span><i><b style="width:${Math.max(2,x.value/max*100)}%"></b></i><strong>${num(x.value)}</strong></div>`).join('')}</div>`;}
function spark(history){if(history.length<2)return '<span class="muted">최소 2회 수집 후 추이가 표시됩니다.</span>';const vals=history.map(x=>x.salePrice).filter(v=>v!=null),min=Math.min(...vals),max=Math.max(...vals),w=280,h=54;const pts=history.map((x,i)=>`${i/(history.length-1)*w},${h-5-(x.salePrice-min)/Math.max(1,max-min)*(h-14)}`).join(' ');return `<svg viewBox="0 0 ${w} ${h}" role="img"><polyline points="${pts}" fill="none" stroke="#5b5ce2" stroke-width="3"/><text x="0" y="12">${num(max)}</text><text x="0" y="52">${num(min)}</text></svg>`;}
function renderTrend(history){if(!history.length){$('#price-chart').textContent='수집 이력이 아직 없습니다.';return;}$('#price-chart').innerHTML=spark(history);const last=history.at(-1);$('#trend-meta').textContent=`최근 판매가 ${num(last.salePrice)} · 소비자가 ${num(last.listPrice)} · 구매평 ${num(last.reviewCount)} · 평균 별점 ${num(last.rating)} (별점 없는 구매평은 평균에서 제외)`;}
async function loadAnalytics(productId){const data=await request('/api/analytics'+(productId?'?productId='+encodeURIComponent(productId):''));if(!productId){analyticsData=data;$('#category-chart').innerHTML=svgBars(data.categories);$('#discounts').innerHTML=data.discounts.length?data.discounts.map(p=>`<tr><td>${esc(p.id)} ${esc(p.name)}</td><td>${num(p.salePrice)}</td><td>${num(p.listPrice)}</td><td>${num(p.discount)}%</td></tr>`).join(''):'<tr><td colspan="4" class="empty">할인 상품이 없습니다.</td></tr>';$('#movers').innerHTML=data.movers.length?data.movers.map(p=>`<button class="mover" data-product="${esc(p.id)}"><span>${esc(p.name)}</span><b>${num(p.change)}</b></button>`).join(''):'변동 이력이 쌓이면 표시됩니다.';}else renderTrend(data.history);}
async function load(){const [summary,list]=await Promise.all([request('/api/summary'),request('/api/products?'+query())]);model=list;const cats=[...new Set(model.items.map(p=>p.category).filter(Boolean))].sort();const selected=$('#category').value;$('#category').innerHTML='<option value="">전체 카테고리</option>'+cats.map(x=>`<option value="${esc(x)}" ${x===selected?'selected':''}>${esc(x)}</option>`).join('');$('#total').textContent=summary.total??0;$('#available').textContent=summary.available??0;$('#soldout').textContent=summary.soldout??0;$('#deleted').textContent=summary.deleted??0;$('#last-seen').textContent=summary.lastSeen?`마지막 상품 확인: ${date(summary.lastSeen)}`:'아직 수집한 상품이 없습니다.';$('#collect').disabled=summary.collecting;$('#collect').textContent=summary.collecting?'수집 중...':'전체 다시 수집';$('#notice').textContent=summary.collecting?'전체 카테고리와 모든 페이지를 수집 중입니다.':'';render();await loadAnalytics();}
async function loadSelector(){const summary=await request('/api/summary');const pages=await Promise.all(Array.from({length:Math.ceil((summary.total||0)/100)},(_,i)=>request(`/api/products?page=${i+1}&pageSize=100`)));const all=pages.flatMap(x=>x.items);$('#trend-product').innerHTML='<option value="">상품을 선택하세요</option>'+all.map(p=>`<option value="${esc(p.id)}">${esc(p.id)} · ${esc(p.name)}</option>`).join('');}
async function boot(){const auth=await request('/api/auth');if(auth.required&&!auth.authorized){$('#login').classList.remove('hidden');return;}$('#app').classList.remove('hidden');await load();await loadSelector();}
$('#login-form').onsubmit=async e=>{e.preventDefault();try{await request('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token:$('#token').value})});$('#login').classList.add('hidden');$('#app').classList.remove('hidden');await load();await loadSelector();}catch(e){$('#login-error').textContent=e.message;}};$('#logout').onclick=async()=>{await request('/api/logout',{method:'POST'});location.reload();};$('#collect').onclick=async()=>{try{await request('/api/collect',{method:'POST'});page=1;await load();await loadSelector();}catch(e){$('#notice').textContent=e.message;}};['category','state'].forEach(id=>$('#'+id).onchange=()=>{page=1;load();});$('#search').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{page=1;load();},300);};$('#prev').onclick=()=>{page--;load();};$('#next').onclick=()=>{page++;load();};$('#trend-product').onchange=e=>e.target.value?loadAnalytics(e.target.value):($('#price-chart').textContent='상품을 선택하세요');document.addEventListener('click',e=>{const p=e.target.closest('[data-product]')?.dataset.product;if(p){$('#trend-product').value=p;loadAnalytics(p);document.querySelector('#price-chart').scrollIntoView({behavior:'smooth',block:'center'});}});boot().catch(e=>console.error(e));
