const $=s=>document.querySelector(s); let products=[]; let timer;
const DEFAULT_IMAGE='https://img.echosting.cafe24.com/thumb/img_product_big.gif';
const fmt=n=>n==null?'-':new Intl.NumberFormat('ko-KR').format(n)+'원';
const date=v=>v?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'-';
function escape(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function imageSrc(p){return !p.image||p.image.includes('ico_mo_arrow_left.png')?DEFAULT_IMAGE:p.image;}
async function request(url,options){const res=await fetch(url,options);if(res.status===401){$('#app').classList.add('hidden');$('#login').classList.remove('hidden');throw new Error('로그인이 필요합니다.');}const data=await res.json();if(!res.ok)throw new Error(data.error||'요청 실패');return data;}
function render(){const q=$('#search').value.toLowerCase(),cat=$('#category').value,state=$('#state').value;const rows=products.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(!cat||p.category===cat)&&(!state||(state==='available'?p.active&&!p.soldOut:state==='soldout'?p.soldOut:!p.active)));$('#count').textContent=`${rows.length}개`;$('#products').innerHTML=rows.length?rows.map(p=>{const image=imageSrc(p);return `<tr><td><div class="product"><button class="image-button" type="button" data-image="${escape(image)}" data-name="${escape(p.name)}" aria-label="${escape(p.name)} 이미지 크게 보기"><img src="${escape(image)}" alt="${escape(p.name)}"></button><div><a href="${escape(p.url)}" target="_blank" rel="noreferrer">${escape(p.name)}</a><div class="meta">ID ${escape(p.id)}</div></div></div></td><td>${escape(p.category||'-')} </td><td>${fmt(p.salePrice??p.price)}</td><td><span class="badge ${!p.active?'inactive':p.soldOut?'soldout':'available'}">${!p.active?'목록 제외':p.soldOut?'품절':'판매 중'}</span></td><td>${date(p.lastSeenAt)}</td></tr>`}).join(''):'<tr><td colspan="5" class="empty">조건에 맞는 상품이 없습니다.</td></tr>';}
async function load(){const [list,summary]=await Promise.all([request('/api/products'),request('/api/summary')]);products=list;const cats=[...new Set(products.map(p=>p.category).filter(Boolean))];const selected=$('#category').value;$('#category').innerHTML='<option value="">전체 카테고리</option>'+cats.map(c=>`<option ${c===selected?'selected':''}>${escape(c)}</option>`).join('');$('#total').textContent=summary.total??0;$('#available').textContent=summary.available??0;$('#soldout').textContent=summary.soldout??0;$('#run').textContent=summary.lastRun?.status==='running'?'수집 중':summary.lastRun?.status==='success'?'완료':'-';$('#last-seen').textContent=summary.last_seen?`마지막 상품 확인: ${date(summary.last_seen)}`:'아직 수집한 상품이 없습니다.';$('#collect').disabled=summary.collecting;$('#collect').textContent=summary.collecting?'수집 중...':'지금 수집';if(summary.collecting){$('#notice').textContent=summary.progress?.total?`${summary.progress.scanned}/${summary.progress.total} 상품 수집 중`:'목록 확인 중';clearTimeout(timer);timer=setTimeout(load,2500);}else $('#notice').textContent='';render();}
async function boot(){const auth=await request('/api/auth');if(auth.required&&!auth.authorized){$('#login').classList.remove('hidden');return;}$('#app').classList.remove('hidden');await load();}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();try{await request('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token:$('#token').value})});$('#login').classList.add('hidden');$('#app').classList.remove('hidden');await load();}catch(e){$('#login-error').textContent=e.message;}});$('#logout').onclick=async()=>{await request('/api/logout',{method:'POST'});location.reload();};$('#collect').onclick=async()=>{try{await request('/api/collect',{method:'POST'});await load();}catch(e){$('#notice').textContent=e.message;}};['search','category','state'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',render));document.addEventListener('click',e=>{const trigger=e.target.closest('.image-button');if(trigger){$('#image-modal img').src=trigger.dataset.image;$('#image-modal img').alt=trigger.dataset.name;$('#image-modal-title').textContent=trigger.dataset.name;$('#image-modal').classList.remove('hidden');}if(e.target.closest('[data-close-modal]'))$('#image-modal').classList.add('hidden');});document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#image-modal').classList.add('hidden');});boot().catch(e=>console.error(e));











