import { init,startRun,endRun,upsertProduct,markInactive,appendCsvSnapshot,upsertReviews,close } from './store.js';
export const ORIGIN='https://vibecodinguniv.cafe24.com';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const decode=v=>String(v??'').replaceAll('&amp;','&').replaceAll('&#39;',"'").replaceAll('&quot;','"').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n));
const text=h=>decode(h.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi,'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim());
const attr=(h,key)=>new RegExp(`<meta[^>]+(?:property|name)=["']${key}["'][^>]+content=["']([^"']+)["']|<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${key}["']`,'i').exec(h)?.slice(1).find(Boolean);
const absolute=v=>v?new URL(decode(v),ORIGIN).href:null;
const number=v=>{const n=Number(String(v??'').replace(/[^0-9]/g,''));return Number.isFinite(n)&&n>0?n:null;};
async function fetchPage(url){const r=await fetch(url,{headers:{'user-agent':'VibecodingProductMonitor/2.0 (public catalog monitor)'},signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.text();}
function categories(home){const xs=[...home.matchAll(/<a\b[^>]*href=["'](\/category\/[^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)].map(([,href,label])=>({url:absolute(href),name:text(label)})).filter(x=>x.name&&x.name.length<40&&!/고객센터|community/i.test(x.name));return [...new Map(xs.map(x=>[x.url,x])).values()];}
function productUrls(html){const xs=[...html.matchAll(/href=["']([^"']*\/product\/[^"']+?\/(\d+)(?:\/[^"']*)?)["']/gi)].map(([,url,id])=>({id,url:absolute(url)}));return [...new Map(xs.map(x=>[x.id,x])).values()];}
function photos(html){return new Map([...html.matchAll(/<div class=["']thumbnail["']>\s*<a[^>]+href=["'][^"']*\/product\/[^"']+?\/(\d+)\/[^"']*["'][^>]*>\s*<img src=["']([^"']+)["']/gi)].map(([,id,image])=>[id,absolute(image)]).filter(([,image])=>image&&/ecimg\.cafe24img\.com/i.test(image)));}
function pagesFor(categoryUrl,html){const nums=[...html.matchAll(/[?&]page=(\d+)/g)].map(m=>+m[1]);const max=Math.max(1,...nums);return Array.from({length:max},(_,i)=>{const u=new URL(categoryUrl);if(i)u.searchParams.set('page',String(i+1));return u.href;});}
async function reviewIndex(){try{const js=await fetchPage('https://ecimg.cafe24img.com/pg3354b17981525095/vibecodinguniv/web/upload/reviews_v2.js');const start=js.indexOf('VCU_REVIEWS');const eq=js.indexOf('=',start);const end=js.lastIndexOf('};');const payload=JSON.parse(js.slice(eq+1,end+1));const map=new Map();for(const r of payload.reviews||[]){const id=String(r.product_no);const a=map.get(id)||{reviews:[],reviewCount:0,rated:[]};a.reviews.push(r);a.reviewCount++;if(typeof r.rating==='number')a.rated.push(r.rating);map.set(id,a);}for(const a of map.values())a.rating=a.rated.length?Number((a.rated.reduce((s,v)=>s+v,0)/a.rated.length).toFixed(2)):null;return map;}catch(error){console.error('구매평 데이터 수집 실패',error.message);return new Map();}}
function extractDetail(html,category,fallback,review){const id=/\/product\/[^/]+\/(\d+)/.exec(fallback.url)?.[1]??fallback.id;const name=decode((attr(html,'og:title')??'').replace(/\s*-\s*바이브코딩대학\s*$/,'').trim())||`상품 ${id}`;const salePrice=number(html.match(/id=["']product_price_text["'][^>]*>([\s\S]*?)<\/strong>/i)?.[1])??number(attr(html,'product:price:amount'));const listPrice=number(html.match(/id=["'](?:span_)?product_price_custom["'][\s\S]*?<strike>([\s\S]*?)<\/strike>/i)?.[1]);const image=fallback.image??absolute(attr(html,'og:image'));const area=html.match(/<div\b[^>]*id=["']prdDetail["'][^>]*>([\s\S]*?)<\/div>\s*<\/div>/i)?.[1]??'';return{id,name,url:fallback.url,image,category,listPrice,salePrice,soldOut:/(?:is_soldout_icon|is_soldout)\s*=\s*['"]T['"]/i.test(html),reviewCount:review?.reviewCount??null,rating:review?.rating??null,description:text(area).slice(0,2000)||null};}
export async function collect({trigger='manual',onProgress=()=>{}}={}){await init();const runId=await startRun(trigger);let scanned=0,added=0,changed=0;const seen=[],csvRows=[];try{const home=await fetchPage(ORIGIN+'/');const cats=categories(home);if(!cats.length)throw new Error('홈페이지에서 카테고리를 찾지 못했습니다.');const reviews=await reviewIndex();await upsertReviews([...reviews.values()].flatMap(x=>x.reviews));const unique=new Map(productUrls(home).map(x=>[x.id,{...x,category:'기타 상품'}]));const photoMap=new Map();for(const cat of cats){onProgress({stage:'category',category:cat.name});const first=await fetchPage(cat.url);for(const pageUrl of pagesFor(cat.url,first)){const page=pageUrl===cat.url?first:await fetchPage(pageUrl);for(const item of productUrls(page))unique.set(item.id,{...item,category:cat.name});for(const [id,image] of photos(page))photoMap.set(id,image);await delay(120);}}
const items=[...unique.values()].map(x=>({...x,image:photoMap.get(x.id)??null}));let cursor=0;async function worker(){while(true){const i=cursor++;if(i>=items.length)return;const item=items[i];onProgress({stage:'product',scanned,total:items.length,name:item.id});try{const result=await upsertProduct(extractDetail(await fetchPage(item.url),item.category,item,reviews.get(item.id)),runId);scanned++;if(result.event==='new')added++;if(result.event!=='new'&&result.event!=='unchanged')changed++;seen.push(item.id);csvRows.push(result.record);}catch(error){console.error('상품 수집 실패',item.url,error.message);}await delay(70);}}
await Promise.all(Array.from({length:8},worker));const removed=await markInactive(seen,runId);csvRows.push(...removed);await appendCsvSnapshot(csvRows);const result={status:'success',scanned,added,changed,deleted:removed.length};await endRun(runId,result);return{...result,runId,csvRows:csvRows.length};}catch(error){const result={status:'failed',scanned,added,changed,error:error.message};await endRun(runId,result);throw error;}finally{await close();}}
